# THIS FILE IS AUTOMATICALLY GENERATED.
# Disclaimer: Please test this file before using in production.
"""
Generated blueprint DSL (.py)
"""

import json  # no_qa
import os  # no_qa

from calm.dsl.builtins import CalmTask as CalmVarTask
from calm.dsl.builtins import *  # no_qa
from calm.dsl.runbooks import CalmEndpoint as Endpoint

# Secret Variables

BP_CRED_NUTANIX_PASSWORD = read_local_file("BP_CRED_NUTANIX_PASSWORD")
BP_CRED_PLAYER_PASSWORD = read_local_file("BP_CRED_PLAYER_PASSWORD")
Profile_Default_variable_TOKEN = read_local_file("Profile_Default_variable_TOKEN")
Profile_Default_variable_EMAILTOKEN = read_local_file(
    "Profile_Default_variable_EMAILTOKEN"
)
Profile_Default_variable_PLANNER_PASSWORD = read_local_file(
    "Profile_Default_variable_PLANNER_PASSWORD"
)
Profile_Default_variable_PC_PASSWORD = read_local_file(
    "Profile_Default_variable_PC_PASSWORD"
)

# Credentials
BP_CRED_NUTANIX = basic_cred(
    "nutanix",
    BP_CRED_NUTANIX_PASSWORD,
    name="NUTANIX",
    type="PASSWORD",
    default=True,
)
BP_CRED_PLAYER = basic_cred(
    "player",
    BP_CRED_PLAYER_PASSWORD,
    name="PLAYER",
    type="PASSWORD",
)
# Endpoints
AD = Endpoint.use_existing("AD")


Ubuntu2404 = vm_disk_package(
    name="Ubuntu2404",
    description="",
    config={
        "name": "Ubuntu2404",
        "image": {
            "name": "Ubuntu2404",
            "type": "DISK_IMAGE",
            "source": "https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img",
            "architecture": "X86_64",
        },
        "product": {"name": "Ubuntu", "version": "24.04"},
        "checksum": {},
    },
)


class Game(Service):

    TEMPLATES = CalmVariable.Simple(
        "", label="", is_mandatory=False, is_hidden=False, runtime=False, description=""
    )

    RECIPIENTS_LIST = CalmVariable.Simple(
        "", label="", is_mandatory=False, is_hidden=True, runtime=False, description=""
    )

    ProjectUUID = CalmVariable.Simple(
        "", label="", is_mandatory=False, is_hidden=True, runtime=False, description=""
    )

    CLUSTERUUID = CalmVariable.Simple(
        "", label="", is_mandatory=False, is_hidden=True, runtime=False, description=""
    )

    CLUSTERNAME = CalmVariable.Simple(
        "", label="", is_mandatory=False, is_hidden=True, runtime=False, description=""
    )

    SECONDARY_SUBNET = CalmVariable.Simple(
        "", label="", is_mandatory=False, is_hidden=True, runtime=False, description=""
    )

    PRIMARY_SUBNET = CalmVariable.Simple(
        "", label="", is_mandatory=False, is_hidden=True, runtime=False, description=""
    )

    @action
    def __create__(type="system"):
        """System action for creating an application"""

        CalmTask.Exec.ssh(
            name="Start dascboard server",
            filename=os.path.join(
                "scripts_legacy", "Service_Game_Action___create___Task_Startdascboardserver.sh"
            ),
            target=ref(Game),
        )

        CalmTask.Exec.ssh(
            name="Start WSSH",
            filename=os.path.join(
                "scripts_legacy", "Service_Game_Action___create___Task_StartWSSH.sh"
            ),
            target=ref(Game),
        )

    @action
    def __start__(type="system"):
        """System action for starting an application"""

        CalmTask.Exec.ssh(
            name="Add right to run_sh",
            filename=os.path.join(
                "scripts_legacy", "Service_Game_Action___start___Task_Addrighttorun_sh.sh"
            ),
            target=ref(Game),
        )


class EGvmcalm_timeResources(AhvVmResources):

    memory = 8
    vCPUs = 4
    cores_per_vCPU = 1
    disks = [AhvVmDisk.Disk.Scsi.cloneFromVMDiskPackage(Ubuntu2404, bootable=True)]
    nics = [AhvVmNic.NormalNic.ingress("primary", cluster="default")]

    guest_customization = AhvVmGC.CloudInit(
        filename=os.path.join("specs_legacy", "EGvmcalm_time_cloud_init_data.yaml")
    )

    power_state = "ON"
    boot_type = "UEFI"


class EGvmcalm_time(AhvVm):

    name = "EG-vm-@@{calm_time}@@"
    resources = EGvmcalm_timeResources

    categories = {"Environment": "Production"}


class VM(Substrate):

    os_type = "Linux"
    provider_type = "AHV_VM"
    provider_spec = EGvmcalm_time

    provider_spec_editables = read_spec(
        os.path.join("specs_legacy", "VM_create_spec_editables.yaml")
    )
    readiness_probe = readiness_probe(
        connection_type="SSH",
        disabled=False,
        retries="5",
        connection_port=22,
        address="@@{platform.status.resources.nic_list[0].ip_endpoint_list[0].ip}@@",
        delay_secs="30",
        credential=ref(BP_CRED_NUTANIX),
    )

    @action
    def __pre_create__(type="fragment"):

        CalmTask.Exec.powershell(
            name="Check AD connection",
            filename=os.path.join(
                "scripts_legacy",
                "Substrate_VM_Action___pre_create___Task_CheckADconnection.ps1",
            ),
            target_endpoint=ref(AD),
        )

        CalmTask.Exec.escript.py3(
            name="Check Capa planing User",
            filename=os.path.join(
                "scripts_legacy",
                "Substrate_VM_Action___pre_create___Task_CheckCapaplaningUser.py",
            ),
            target=ref(VM),
        )


class CreateGameContent(Package):

    name = "Create Game Content"
    services = [ref(Game)]

    @action
    def __install__(type="system"):

        CalmTask.Exec.escript.py3(
            name="Activate policy engine",
            filename=os.path.join(
                "scripts_legacy",
                "Package_CreateGameContent_Action___install___Task_Activatepolicyengine.py",
            ),
            target=ref(Game),
        )

        CalmTask.SetVariable.escript.py3(
            name="Get Cluster",
            filename=os.path.join(
                "scripts_legacy",
                "Package_CreateGameContent_Action___install___Task_GetCluster.py",
            ),
            target=ref(Game),
            variables=["CLUSTERNAME", "CLUSTERUUID"],
        )

        CalmTask.Exec.ssh(
            name="Clone Git Repo",
            filename=os.path.join(
                "scripts_legacy",
                "Package_CreateGameContent_Action___install___Task_CloneGitRepo.sh",
            ),
            target=ref(Game),
        )

        CalmTask.Exec.ssh(
            name="Create Pyhton venv",
            filename=os.path.join(
                "scripts_legacy",
                "Package_CreateGameContent_Action___install___Task_CreatePyhtonvenv.sh",
            ),
            target=ref(Game),
        )

        CalmTask.Exec.ssh(
            name="Install Python modules",
            filename=os.path.join(
                "scripts_legacy",
                "Package_CreateGameContent_Action___install___Task_InstallPythonmodules.sh",
            ),
            target=ref(Game),
        )

        CalmTask.Exec.ssh(
            name="Remove 1 host",
            filename=os.path.join(
                "scripts_legacy",
                "Package_CreateGameContent_Action___install___Task_Remove1host.sh",
            ),
            target=ref(Game),
        )

        CalmTask.Exec.escript.py3(
            name="Wait for cluster health",
            filename=os.path.join(
                "scripts_legacy",
                "Package_CreateGameContent_Action___install___Task_ClusterHealth.py",
            ),
            target=ref(Game),
        )

        CalmTask.Delay(name="Wait for ssh server", delay_seconds=30, target=ref(Game))

        CalmTask.Exec.ssh(
            name="Rename Network if Needed",
            filename=os.path.join(
                "scripts_legacy",
                "Package_CreateGameContent_Action___install___Task_RenameNetworkifNeeded.sh",
            ),
            target=ref(Game),
        )

        CalmTask.SetVariable.ssh(
            name="GetNetworkNames",
            filename=os.path.join(
                "scripts_legacy",
                "Package_CreateGameContent_Action___install___Task_GetNetworkNames.sh",
            ),
            target=ref(Game),
            variables=["PRIMARY_SUBNET", "SECONDARY_SUBNET"],
        )

        CalmTask.Exec.ssh(
            name="Migrate Secondary subnet to advanced",
            filename=os.path.join(
                "scripts_legacy",
                "Package_CreateGameContent_Action___install___Task_MigrateSecondarysubnettoadvanced.sh",
            ),
            target=ref(Game),
        )

        CalmTask.Exec.ssh(
            name="Install Docker",
            filename=os.path.join(
                "scripts_legacy",
                "Package_CreateGameContent_Action___install___Task_InstallDocker.sh",
            ),
            cred=ref(BP_CRED_NUTANIX),
            target=ref(Game),
        )

        CalmTask.Exec.ssh(
            name="Install CalmDSL",
            filename=os.path.join(
                "scripts_legacy",
                "Package_CreateGameContent_Action___install___Task_InstallCalmDSL.sh",
            ),
            target=ref(Game),
        )

        CalmTask.Exec.ssh(
            name="Create Local users",
            filename=os.path.join(
                "scripts_legacy",
                "Package_CreateGameContent_Action___install___Task_CreateLocalusers.sh",
            ),
            target=ref(Game),
        )

        CalmTask.Exec.powershell(
            name="Add AD users",
            filename=os.path.join(
                "scripts_legacy",
                "Package_CreateGameContent_Action___install___Task_AddADusers.ps1",
            ),
            target_endpoint=ref(AD),
        )

        CalmTask.SetVariable.ssh(
            name="Create Project",
            filename=os.path.join(
                "scripts_legacy",
                "Package_CreateGameContent_Action___install___Task_CreateProject.sh",
            ),
            target=ref(Game),
            variables=["ProjectUUID"],
        )

        CalmTask.Exec.ssh(
            name="Init CalmDSL",
            filename=os.path.join(
                "scripts_legacy",
                "Package_CreateGameContent_Action___install___Task_InitCalmDSL.sh",
            ),
            target=ref(Game),
        )

        CalmTask.Exec.ssh(
            name="Create Prod VMs",
            filename=os.path.join(
                "scripts_legacy",
                "Package_CreateGameContent_Action___install___Task_CreateProdVMs.sh",
            ),
            target=ref(Game),
        )

        CalmTask.Exec.ssh(
            name="Launch Inventory",
            filename=os.path.join(
                "scripts_legacy",
                "Package_CreateGameContent_Action___install___Task_LaunchInventory.sh",
            ),
            target=ref(Game),
        )

        CalmTask.Exec.escript.py3(
            name="Create Jumphost",
            filename=os.path.join(
                "scripts_legacy",
                "Package_CreateGameContent_Action___install___Task_CreateJumphost.py",
            ),
            target=ref(Game),
        )

        CalmTask.Exec.ssh(
            name="Push BP on Calm",
            filename=os.path.join(
                "scripts_legacy",
                "Package_CreateGameContent_Action___install___Task_PushBPonCalm.sh",
            ),
            target=ref(Game),
        )

        CalmTask.Exec.ssh(
            name="Create Subnet TestNetwork",
            filename=os.path.join(
                "scripts_legacy",
                "Package_CreateGameContent_Action___install___Task_CreateSubnetTestNetwork.sh",
            ),
            target=ref(Game),
        )

        CalmTask.Exec.ssh(
            name="Create fake BPs",
            filename=os.path.join(
                "scripts_legacy",
                "Package_CreateGameContent_Action___install___Task_CreatefakeBPs.sh",
            ),
            target=ref(Game),
        )

        CalmTask.Exec.ssh(
            name="Create venv and dl modules",
            filename=os.path.join(
                "scripts_legacy",
                "Package_CreateGameContent_Action___install___Task_Createvenvanddlmodules.sh",
            ),
            target=ref(Game),
        )

        CalmTask.Exec.ssh(
            name="Create game env file",
            filename=os.path.join(
                "scripts_legacy",
                "Package_CreateGameContent_Action___install___Task_Creategameenvfile.sh",
            ),
            target=ref(Game),
        )

        CalmTask.Exec.ssh(
            name="Initialize game",
            filename=os.path.join(
                "scripts_legacy",
                "Package_CreateGameContent_Action___install___Task_Initializegame.sh",
            ),
            target=ref(Game),
        )

        CalmTask.SetVariable.ssh(
            name="Get emails list",
            filename=os.path.join(
                "scripts_legacy",
                "Package_CreateGameContent_Action___install___Task_Getemailslist.sh",
            ),
            target=ref(Game),
            variables=["TEMPLATES"],
        )


class deployment_e777f451(Deployment):

    min_replicas = "1"
    max_replicas = "1"
    default_replicas = "1"

    packages = [ref(CreateGameContent)]
    substrate = ref(VM)


class Default(Profile):

    deployments = [deployment_e777f451]

    GIT_BRANCH = CalmVariable.Simple(
        "main",
        label="Git Branch",
        is_mandatory=False,
        is_hidden=False,
        runtime=True,
        description="",
    )

    GIT_URL = CalmVariable.Simple(
        "https://github.com/r0w/ntnx-escape-game",
        label="Git Escape Game URL",
        is_mandatory=False,
        is_hidden=False,
        runtime=True,
        description="",
    )

    CLUSTERNAME = CalmVariable.Simple(
        "", label="", is_mandatory=False, is_hidden=True, runtime=False, description=""
    )

    DockerRegistry = CalmVariable.Simple(
        "registry.nutanixdemo.com/docker.io",
        label="",
        is_mandatory=False,
        is_hidden=True,
        runtime=False,
        description="Registry path, without end /",
    )

    TOKEN = CalmVariable.Simple.Secret(
        Profile_Default_variable_TOKEN,
        label="",
        is_mandatory=False,
        is_hidden=False,
        runtime=False,
        description="",
    )

    EMAILTOKEN = CalmVariable.Simple.Secret(
        Profile_Default_variable_EMAILTOKEN,
        label="Token for Mailtrap",
        is_mandatory=False,
        is_hidden=False,
        runtime=True,
        description="Ask the Escape Game Dev Team to get it.\nUse this if you want to send emails via Day 2 Actions.",
    )

    PLANNER_PASSWORD = CalmVariable.Simple.Secret(
        Profile_Default_variable_PLANNER_PASSWORD,
        label="Password for user 'Planner'",
        is_mandatory=False,
        is_hidden=False,
        runtime=True,
        description="Ask the Escape Game Dev Team to get it.",
    )

    PC_PASSWORD = CalmVariable.Simple.Secret(
        Profile_Default_variable_PC_PASSWORD,
        label="Prism Central Admin Password",
        is_mandatory=True,
        is_hidden=False,
        runtime=True,
        description="",
    )

    PC_USERNAME = CalmVariable.Simple(
        "",
        label="Prism Central Admin user",
        is_mandatory=False,
        is_hidden=False,
        runtime=True,
        description="",
    )

    PC_IP = CalmVariable.Simple(
        "",
        label="Prism Central IP",
        is_mandatory=False,
        is_hidden=False,
        runtime=True,
        description="",
    )

    OLDPC = CalmVariable.Simple(
        "",
        label="",
        is_mandatory=False,
        is_hidden=True,
        runtime=False,
        description="",
    )

    OLDPC_USER = CalmVariable.Simple(
        "planner",
        label="",
        is_mandatory=False,
        is_hidden=True,
        runtime=False,
        description="",
    )

    TIMEZONE = CalmVariable.WithOptions(
        [
            "UTC",
            "Europe/Paris",
            "Europe/London",
            "America/New_York",
            "America/Los_Angeles",
            "America/Sao_Paulo",
            "Asia/Dubai",
            "Asia/Tokyo",
            "Australia/Sydney",
        ],
        label="Time Zone",
        default="UTC",
        regex="^.*$",
        validate_regex=False,
        is_mandatory=True,
        is_hidden=False,
        runtime=True,
        description="Will be used on the scoreboard",
    )

    @action
    def RestartAllServers(
        name="Restart All Servers",
    ):

        CalmTask.Exec.ssh(
            name="Restart Dashboard",
            filename=os.path.join(
                "scripts_legacy",
                "Profile_Default_Action_RestartAllServers_Task_RestartDashboard.sh",
            ),
            target=ref(Game),
        )

        CalmTask.Exec.ssh(
            name="Restart WSSH",
            filename=os.path.join(
                "scripts_legacy",
                "Profile_Default_Action_RestartAllServers_Task_RestartWSSH.sh",
            ),
            target=ref(Game),
        )

    @action
    def SendInvitationsEmails(
        name="Send Invitations Emails",
    ):

        Template = CalmVariable.WithOptions.FromTask(
            CalmVarTask.Exec.escript.py3(
                name="",
                filename=os.path.join(
                    "scripts_legacy",
                    "Profile_Default_Action_SendInvitationsEmails_variable_Template_Task_SampleTask.py",
                ),
            ),
            label="",
            is_mandatory=False,
            is_hidden=False,
            description="",
        )
        RECIPIENTS = CalmVariable.Simple(
            "",
            label="Recipients",
            is_mandatory=False,
            is_hidden=False,
            runtime=True,
            description="Use only email addresses, with comma as separator.",
        )

        CalmTask.Exec.ssh(
            name="Send Email",
            filename=os.path.join(
                "scripts_legacy",
                "Profile_Default_Action_SendInvitationsEmails_Task_SendEmail.sh",
            ),
            target=ref(Game),
        )

        CalmTask.SetVariable.escript.py3(
            name="Set Variables",
            filename=os.path.join(
                "scripts_legacy",
                "Profile_Default_Action_SendInvitationsEmails_Task_SetVariables.py",
            ),
            target=ref(Game),
            variables=["RECIPIENTS_LIST"],
        )

    @action
    def SendSummaryEmail(
        name="Send Summary Email",
    ):

        Template = CalmVariable.WithOptions.FromTask(
            CalmVarTask.Exec.escript.py3(
                name="",
                filename=os.path.join(
                    "scripts_legacy",
                    "Profile_Default_Action_SendSummaryEmail_variable_Template_Task_SampleTask.py",
                ),
            ),
            label="",
            is_mandatory=False,
            is_hidden=False,
            description="",
        )

        CalmTask.Exec.ssh(
            name="Send Summary Emails",
            filename=os.path.join(
                "scripts_legacy",
                "Profile_Default_Action_SendSummaryEmail_Task_SendSummaryEmails.sh",
            ),
            target=ref(Game),
        )

    @action
    def ChangeUserStage(
        name="Change User Stage",
    ):
        """Force user stage change. This is in development stage, please do not use it without approval of Escape Game Team."""

        NewStage = CalmVariable.Simple.int(
            "",
            label="New stage",
            regex="^[\\d]*$",
            validate_regex=False,
            is_mandatory=True,
            is_hidden=False,
            runtime=True,
            description="",
        )
        Trigram = CalmVariable.Simple(
            "",
            label="",
            is_mandatory=True,
            is_hidden=False,
            runtime=True,
            description="",
        )

        CalmTask.Exec.ssh(
            name="Change Stage",
            filename=os.path.join(
                "scripts_legacy", "Profile_Default_Action_ChangeUserStage_Task_ChangeStage.sh"
            ),
            target=ref(Game),
        )

    @action
    def UpdateGame(
        name="Update Game",
    ):
        """Pull modifications from git repository."""

        CalmTask.Exec.ssh(
            name="git pull",
            filename=os.path.join(
                "scripts_legacy", "Profile_Default_Action_UpdateGame_Task_gitpull.sh"
            ),
            target=ref(Game),
        )

    @action
    def SetCombinedScoreboards(
        name="Set Combined Scoreboards",
    ):
        """Configure the list of all scoreboards to be combined when multiple PCs and Escape Games are deployed.

        For each game deployed, we need the IP address of the URL for accessing the game's scoreboard (not the entire URL). Then simply enter the list of all IP addresses separated by commas."""

        SCOREBOARDSIPS = CalmVariable.Simple(
            "",
            label="",
            regex="^.*$",
            validate_regex=False,
            is_mandatory=False,
            is_hidden=False,
            runtime=True,
            description="Use only IP addresses, with comma as separator.",
        )

        CalmTask.Exec.ssh(
            name="Set Scoreboards IPs List",
            filename=os.path.join(
                "scripts_legacy",
                "Profile_Default_Action_SetCombinedScoreboards_Task_SetScoreboardsIPsList.sh",
            ),
            target=ref(Game),
        )

        CalmTask.SetVariable.escript.py3(
            name="Set Variable",
            filename=os.path.join(
                "scripts_legacy",
                "Profile_Default_Action_SetCombinedScoreboards_Task_SetVariable.py",
            ),
            target=ref(Game),
            variables=["COMBINEDSCOREBOARDS"],
        )

    @action
    def UpdateNodeSerialNumber(
        name="Update Node Serial Number",
    ):
        """#!/bin/bash
        cd ntnx-escape-game
        source .venv/bin/activate
        python main.py -setNodeSerial @@{SerialNumber}@@"""

        SerialNumber = CalmVariable.Simple(
            "",
            label="",
            is_mandatory=False,
            is_hidden=False,
            runtime=True,
            description="",
        )


class EGBlueprintInstallation(Blueprint):
    """Deploy escape game on a brand new HPOC. When deployed :

    - Game will be available on  http://@@{VM.address}@@:8080
    - Scoreboard will be available on http://@@{VM.address}@@:8080/scoreboard"""

    services = [Game]
    packages = [Ubuntu2404, CreateGameContent]
    substrates = [VM]
    profiles = [Default]
    credentials = [BP_CRED_NUTANIX, BP_CRED_PLAYER]
